version: "3"

services:

  api:
    environment:
      - VIRTUAL_HOST=api.dsri.semanticscience.org
      - LETSENCRYPT_HOST=api.dsri.semanticscience.org
      - VIRTUAL_PORT=80

  mysql:
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    environment:
      - PMA_ABSOLUTE_URI=https://admin.dsri.semanticscience.org
      - VIRTUAL_HOST=admin.dsri.semanticscience.org
      - LETSENCRYPT_HOST=admin.dsri.semanticscience.org
      - VIRTUAL_PORT=80
