version: "3"

services:

  website:
    build: website
    ports:
      - 3000:3000
    volumes:
      - ./website:/app/website
    environment:
      - API_URL=https://api.dsri.maastrichtuniversity.nl