version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=dsri.137.120.31.102.nip.io
      - VIRTUAL_PORT=3000
    # volumes:
    #   - ./v4-website:/app/website
