version: "3"

services:
  # Frontend deployed on GitHub Pages by a GitHub Action 

  # server:
  #   restart: unless-stopped
  #   build: server
  #   environment:
  #     - SQL_URL=mysql:3306
  #     - PASSWORD=${PASSWORD-password}

  fastapi:
    build: ./fastapi
    restart: unless-stopped
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      - SQL_URL=mysql://dsri-user:${PASSWORD-password}@mysql:3306/dsri-db
      # - PASSWORD=${PASSWORD-password}


  mysql:
    restart: unless-stopped
    image: mariadb:10.3
    # image: mysql:5.7
    environment: 
      MYSQL_DATABASE: dsri-db
      MYSQL_ROOT_PASSWORD: ${PASSWORD-password}
      MARIADB_USER: dsri-user
      MARIADB_PASSWORD: ${PASSWORD-password}
      MARIADB_ROOT_PASSWORD: ${PASSWORD-password}
    volumes:
      # - ./server/schemas:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    # ports:
    #   - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_PASSWORD=${PASSWORD-password}
      - MYSQL_ROOT_PASSWORD=${PASSWORD-password}
      - MYSQL_PASSWORD=${PASSWORD-password}
      - PMA_HOST=mysql:3306
