version: "3"

services:

  # server:
  #   build: server
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./server:/app
  #   command: yarn dev

  fastapi:
    ports:
      - 8000:80
    volumes:
      - ./fastapi/api:/app/api
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload

  mysql:
    volumes:
      - ./data:/var/lib/mysql
    # ports:
    #   - 3306:3306

  phpmyadmin:
    ports:
      - 8080:80
