#
#
#

services:
  # Prod frontend is deployed on GitHub Pages by a GitHub Action
  website:
    build: website
    container_name: dsri-website
    environment:
      - VIRTUAL_HOST=${DSRI_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${DSRI_LETSENCRYPT_HOST}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      - VIRTUAL_PORT=80

  # To deploy in prod we use a nginx proxy for docker containers with a companion to enable HTTPS with LetsEncrypt
  # https://github.com/nginx-proxy/nginx-proxy
  # https://github.com/nginx-proxy/acme-companion
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
    #  - ./data/certs:/etc/nginx/certs:ro # use this on your local machine
      - /data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      default: 
        ipv4_address: 172.19.0.4

  # Use letsencrypt to serve HTTPS https://github.com/nginx-proxy/acme-companion
  # Docs: https://github.com/nginx-proxy/acme-companion/wiki/Container-configuration
  nginx-encrypt-https:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - REUSE_KEY=false
      - DEBUG=true
      - DEFAULT_EMAIL=DSRI-SUPPORT-L@maastrichtuniversity.nl
    volumes_from:
      - nginx-proxy:rw
    volumes:
    #  - ./data/certs:/etc/nginx/certs:rw # use this on your local machine
      - /data/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    restart: unless-stopped
    networks:
      default: 
        ipv4_address: 172.19.0.5

  mysql:
    restart: unless-stopped
    image: mariadb:10.3
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: dsri-db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: dsri-user
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    # volumes:
    #  - ./server/cron/backup_database.sh:/app/backup_database.sh
    #  - ./server/cron/backup_database.sh:/app/restore_backup.sh
    # docker-compose exec mysql chown mysql: /backup
    #  - ./server/schemas:/docker-entrypoint-initdb.d
    command: --max-allowed-packet=16M
    volumes:
    #  - ./data/database/data:/var/lib/mysql # use this on your local machine
    #  - ./data/database/backup:/backup # use this on your local machine
      - /data/database/data:/var/lib/mysql
      - /data/database/backup:/backup
    networks:
      default: 
        ipv4_address: 172.19.0.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=mysql:3306
      - PMA_ABSOLUTE_URI=https://${ADMIN_VIRTUAL_HOST}
      - VIRTUAL_HOST=${ADMIN_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${ADMIN_LETSENCRYPT_HOST}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      - VIRTUAL_PORT=80
    restart: unless-stopped
    networks:
      default: 
        ipv4_address: 172.19.0.7

  dsri-api:
    build: ./server
    container_name: dsri-api
    depends_on:
      - mysql
      - phpmyadmin
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - VIRTUAL_HOST=${API_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${API_VIRTUAL_HOST}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      - VIRTUAL_PORT=80
      - SQL_URL=mysql://dsri-user:${DB_PASSWORD}@mysql:3306/dsri-db
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - CLUSTER_URL=${CLUSTER_URL}
      - CLUSTER_API_KEY=${CLUSTER_API_KEY}
      - API_PASSWORD=${API_PASSWORD}
      - ENABLE_CRON=true
    volumes:
    #  - ./data/database/backup:/backup:ro # use this on your local machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /data/database/backup:/backup
      - ./server/api:/app/api
    restart: unless-stopped
    networks:
      default: 
        ipv4_address: 172.19.0.8

  gpu-calendar:
    build: ./gpu-calendar
    container_name: gpu-calendar
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - VIRTUAL_HOST=${CALENDAR_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${CALENDAR_LETSENCRYPT_HOST}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      - VIRTUAL_PORT=80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      default: 
        ipv4_address: 172.19.0.9

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/24"
          gateway: 172.19.0.1

volumes:
  vhost:
  html:
  acme: