version: "3"

services:

  fastapi:
    environment:
      # - VIRTUAL_HOST=api.dsri.semanticscience.org
      # - LETSENCRYPT_HOST=api.dsri.semanticscience.org
      - VIRTUAL_HOST=api.dsri.137.120.31.101.nip.io
      - LETSENCRYPT_HOST=api.dsri.137.120.31.101.nip.io
      - VIRTUAL_PORT=80

  mysql:
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    environment:
      # - PMA_ABSOLUTE_URI=https://admin.dsri.semanticscience.org
      # - VIRTUAL_HOST=admin.dsri.semanticscience.org
      # - LETSENCRYPT_HOST=admin.dsri.semanticscience.org
      - PMA_ABSOLUTE_URI=https://admin.dsri.137.120.31.101.nip.io
      - VIRTUAL_HOST=admin.dsri.137.120.31.101.nip.io
      - LETSENCRYPT_HOST=admin.dsri.137.120.31.101.nip.io
      - VIRTUAL_PORT=80
