version: "3"

services:

  api:
    environment:
      - VIRTUAL_HOST=api.dsri.maastrichtuniversity.nl
      - LETSENCRYPT_HOST=api.dsri.maastrichtuniversity.nl
      - VIRTUAL_PORT=80


  gpu-calendar:
    environment:
      - VIRTUAL_HOST=calendar.dsri.maastrichtuniversity.nl
      - LETSENCRYPT_HOST=calendar.dsri.maastrichtuniversity.nl
      # - VIRTUAL_HOST=calendar.dsri.semanticscience.org
      # - LETSENCRYPT_HOST=calendar.dsri.semanticscience.org
      - VIRTUAL_PORT=80


  mysql:
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/backup

  cronjob:
    volumes:
      - ./backup:/backup
      - ./server/api:/app/api
      - ./server/cron:/app/cron
      - ./server/cron/gpu-notification-cron:/etc/cron.d/gpu-notification-cron

  phpmyadmin:
    environment:
      - PMA_ABSOLUTE_URI=https://admin.dsri.maastrichtuniversity.nl
      - VIRTUAL_HOST=admin.dsri.maastrichtuniversity.nl
      - LETSENCRYPT_HOST=admin.dsri.maastrichtuniversity.nl
      - VIRTUAL_PORT=80
