version: "3"

services:
  # Frontend deployed on GitHub Pages by a GitHub Action 

  mysql:
    restart: unless-stopped
    image: mariadb:10.3
    # image: mysql:5.7
    environment: 
      MYSQL_DATABASE: dsri-db
      MYSQL_ROOT_PASSWORD: ${PASSWORD-password}
      MARIADB_USER: dsri-user
      MARIADB_PASSWORD: ${PASSWORD-password}
      MARIADB_ROOT_PASSWORD: ${PASSWORD-password}
    # volumes:
    #   - ./data:/var/lib/mysql
    #   - ./backup:/backup
    #   - ./server/cron/backup_database.sh:/app/backup_database.sh
    #   - ./server/cron/backup_database.sh:/app/restore_backup.sh
      # docker-compose exec mysql chown mysql: /backup
      # - ./server/schemas:/docker-entrypoint-initdb.d
    command: --max-allowed-packet=16M

  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1
    depends_on:
      - mysql
    environment:
      - PMA_PASSWORD=${PASSWORD-password}
      - MYSQL_ROOT_PASSWORD=${PASSWORD-password}
      - MYSQL_PASSWORD=${PASSWORD-password}
      - PMA_HOST=mysql:3306

  api:
    build: ./server
    restart: unless-stopped
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      - SQL_URL=mysql://dsri-user:${PASSWORD-password}@mysql:3306/dsri-db
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN-xoxb}
      - SLACK_CHANNEL=${SLACK_CHANNEL-UQL6BCQJH}
      - CLUSTER_USER=${CLUSTER_USER-Vincent.Emonet}
      - CLUSTER_PASSWORD=${CLUSTER_PASSWORD-password}
      - API_PASSWORD=${API_PASSWORD-password}


  gpu-calendar:
    build: ./gpu-calendar
    restart: unless-stopped
    depends_on:
      - mysql
      - phpmyadmin
    environment:
      - DB_PASSWORD=${PASSWORD-password}


  # cronjob:
  #   # Same image as the API
  #   build: ./server
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
  #     - phpmyadmin
  #   environment:
  #     - SQL_URL=mysql://dsri-user:${PASSWORD-password}@mysql:3306/dsri-db
  #     - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN-xoxb}
  #     - SLACK_CHANNEL=${SLACK_CHANNEL-UQL6BCQJH}
  #   command: /app/cron/start_cron.sh

  # server:
  #   restart: unless-stopped
  #   build: server
  #   environment:
  #     - SQL_URL=mysql:3306
  #     - PASSWORD=${PASSWORD-password}
