version: "3"

services:

  api:
    ports:
      - 8000:80
    volumes:
      - ./server/api:/app/api
      - ./server/cron:/app/cron
      - ./server/cron/gpu-notification-cron:/etc/cron.d/gpu-notification-cron
    # command: cron -f && uvicorn api.main:app --host 0.0.0.0 --port 80 --reload
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload

  cronjob:
    volumes:
      - ./server/api:/app/api
      - ./server/cron:/app/cron
      - ./server/cron/gpu-notification-cron:/etc/cron.d/gpu-notification-cron
      - ./backup:/backup


  gpu-calendar:
    ports:
      - 8001:80

  mysql:
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/backup
    #   - ./server/cron/backup_database.sh:/app/backup_database.sh
    #   - ./server/cron/backup_database.sh:/app/restore_backup.sh
    # ports:
    #   - 3306:3306

  phpmyadmin:
    ports:
      - 8080:80


  # server:
  #   build: server
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./server:/app
  #   command: yarn dev
