apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nvidia-tensorflow-gpu
spec:
  lookupPolicy:
    local: true
  tags: 
    - name: 19.11-tf2-py3
      from: 
        kind: DockerImage
        name: nvcr.io/nvidia/tensorflow:19.11-tf2-py3