---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: matlab-cpu-nolicense
metadata:
  annotations:
    description: |-
      Start Matlab with a desktop UI, and use your own license to enable
      Matlab (this can be useful when the UM license server does not support the latest
      Matlab release).
      Running on CPU, with admin privileges to install anything you
      need
      
      📂 Use the `/root/persistent` folder to store your data in the
      persistent storage automatically created.
      You can find the persistent storage in the DSRI web UI, go to Administrator view > Storage > Persistent
      Volume Claims
      
      🐳 Visit https://hub.docker.com/r/mathworks/matlab for more details about the image
    iconClass: icon-beaker
    openshift.io/display-name: Matlab with your license
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-matlab
    openshift.io/provider-display-name: Institute of Data Science, UM
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
    tags: matlab,cpu,root,persistent
  name: matlab-cpu-nolicense
  namespace: openshift

objects:
- kind: Secret
  apiVersion: v1
  metadata:
    annotations:
      template.openshift.io/expose-password: "{.data['application-password']}"
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  stringData:
    application-password: "${PASSWORD}"

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "${STORAGE_SIZE}"
    storageClassName: ocs-storagecluster-cephfs

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
      template: matlab-cpu
    name: "${APPLICATION_NAME}"
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: "${APPLICATION_IMAGE}"
      importPolicy:
        scheduled: false
      name: latest

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: "${APPLICATION_NAME}"
        deployment: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deployment: "${APPLICATION_NAME}"
      spec:
        automountServiceAccountToken: false
        containers:
        - args:
          - "${DEPLOYMENT_TYPE}"
          env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: application-password
                name: "${APPLICATION_NAME}"
          image: "${APPLICATION_IMAGE}"
          imagePullPolicy: Always
          name: matlab-container
          ports:
          - containerPort: 8888
            protocol: TCP
          volumeMounts:
          - mountPath: "/root/persistent"
            name: data
          - mountPath: "/dev/shm"
            name: dshm
        securityContext:
          runAsUser: 0
        serviceAccountName: anyuid
        imagePullSecrets:
          - name: harbor-docker-pull-secret
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}"
        - emptyDir:
            medium: Memory
          name: dshm

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: "${APPLICATION_NAME}"
      deployment: "${APPLICATION_NAME}"

- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    host: ''
    port:
      targetPort: 8888-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100

parameters:
- description: Must be unique in the project. It will be used to generate the application
    URL.
  displayName: Application name
  name: APPLICATION_NAME
  required: true
  value: matlab
- description: The password to access the Matlab web UI
  displayName: Matlab UI password
  name: PASSWORD
  required: true
- description: Size of the storage used for Matlab (approximate).
  displayName: Storage size
  name: STORAGE_SIZE
  required: true
  value: 10Gi
- description: See https://hub.docker.com/r/mathworks/matlab for more details
  displayName: Application Docker image
  name: APPLICATION_IMAGE
  required: true
  value: cr.icts.unimaas.nl/dsri_dockerhub/mathworks/matlab:r2024a
- description: "-vnc or -browser"
  displayName: Type of deployment
  name: DEPLOYMENT_TYPE
  required: true
  value: "-browser"