---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: matlab-cpu-nolicense
  annotations:
    openshift.io/display-name: Matlab with your license
    description: |-
      Start Matlab with a desktop UI, and use your own license to enable
      Matlab (this can be useful when the UM license server does not support the latest
      Matlab release).
      Running on CPU, with admin privileges to install anything you
      need
      
      📂 Use the `/root/persistent` folder to store your data in the
      persistent storage automatically created.
      You can find the persistent storage in the DSRI web UI, go to Administrator view > Storage > Persistent
      Volume Claims
      
      🐳 Visit https://hub.docker.com/r/mathworks/matlab for more details about the image
    iconClass: icon-beaker
    tags: matlab,cpu,root,persistent
    openshift.io/provider-display-name: Institute of Data Science, UM
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-matlab
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
labels:
  template: matlab-cpu-nolicense

parameters:
  - name: APPLICATION_NAME
    displayName: Application name
    description: Must be unique in the project. It will be used to generate the application URL.
    value: matlab
    required: true
  - name: APPLICATION_IMAGE
    displayName: Application Docker image
    description: See https://hub.docker.com/r/mathworks/matlab for more details
    value: mathworks/matlab:r2025a
    required: true
  - name: STORAGE_SIZE
    displayName: Storage size
    description: Size of the storage used for Matlab (approximate).
    value: 10Gi
    required: true
  - name: PASSWORD
    displayName: Matlab UI password
    description: The password to access the Matlab web UI
    required: true
  - name: DEPLOYMENT_TYPE
    displayName: Type of deployment
    description: "-vnc or -browser"
    value: "-browser"
    required: true

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
        template: matlab-cpu
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: ${APPLICATION_IMAGE}
          importPolicy:
            scheduled: false

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${STORAGE_SIZE}
      storageClassName: ocs-storagecluster-cephfs

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      selector:
        app: "${APPLICATION_NAME}"
      ports:
        - name: "8888-tcp"
          protocol: TCP
          port: 8888
          targetPort: 8888

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
      port:
        targetPort: "8888-tcp"
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
      annotations:
        template.openshift.io/expose-password: "{.data['application-password']}"
    stringData:
      application-password: "${PASSWORD}"

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: "${APPLICATION_NAME}"
      template:
        metadata:
          labels:
            app: "${APPLICATION_NAME}"
            deployment: "${APPLICATION_NAME}"
        spec:
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 0
          serviceAccountName: anyuid
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: "${APPLICATION_NAME}"
            - name: dshm
              emptyDir:
                medium: Memory
          containers:
            - name: "${APPLICATION_NAME}"
              image: "${APPLICATION_IMAGE}"
              imagePullPolicy: IfNotPresent
              args:
                - "${DEPLOYMENT_TYPE}"
              ports:
                - containerPort: 8888
                  protocol: TCP
              volumeMounts:
                - name: data
                  mountPath: "/root/persistent"
                - name: dshm
                  mountPath: "/dev/shm"
              env:
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: application-password
                      name: "${APPLICATION_NAME}"