---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ants-jupyterlab
  annotations:
    openshift.io/display-name: ANTs with JupyterLab
    description: |-
      Test the local image
      Advanced Normalization Tools (ANTs) 2.6.4 pre-loaded in a JupyterLab workspace. 

      🐳 **Features:**
      - ANTs 2.6.4 (Latest Stable)
      - JupyterLab interface with Python 3.12

      📂 **Persistence:**
      Use the `/root/persistent` folder to store your data. 
      Data stored outside this folder will be lost when the pod restarts.

    iconClass: icon-python
    tags: neuro,ants,mri,jupyter,notebook
    openshift.io/provider-display-name: Research Computing Support, UM
    openshift.io/documentation-url: https://github.com/ANTsX/ANTs
labels:
  template: ants-jupyterlab

parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    value: ants-jupyterlab
    required: true
  - name: APPLICATION_IMAGE
    displayName: ANTs Docker Image
    description: Optimized ANTs 2.6.4 image with JupyterLab.
    value: default-route-openshift-image-registry.apps.dsri2.unimaas.nl/adelina-test2/ants:2.6.4
    required: true
  - name: STORAGE_SIZE
    displayName: Storage Size
    value: 10Gi
    required: true
  - name: PASSWORD
    displayName: JupyterLab Password
    required: true

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      lookupPolicy:
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: ${APPLICATION_IMAGE}
          importPolicy:
            scheduled: false

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${STORAGE_SIZE}
      storageClassName: ocs-storagecluster-cephfs

  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      selector:
        app: "${APPLICATION_NAME}"
      ports:
        - name: "8888-tcp"
          protocol: TCP
          port: 8888
          targetPort: 8888
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
      port:
        targetPort: "8888-tcp"
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    stringData:
      application-password: "${PASSWORD}"

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: "${APPLICATION_NAME}"
      template:
        metadata:
          annotations:
            io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
          labels:
            app: "${APPLICATION_NAME}"
            deployment: "${APPLICATION_NAME}"
        spec:
          serviceAccountName: "anyuid"
          automountServiceAccountToken: false
          securityContext:
            runAsUser: 0
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: "${APPLICATION_NAME}"
          containers:
            - name: "${APPLICATION_NAME}"
              image: "${APPLICATION_IMAGE}"
              imagePullPolicy: Always
              workingDir: /root
              ports:
                - containerPort: 8888
                  protocol: TCP
              volumeMounts:
                - name: data
                  mountPath: /root/persistent
              env:
                - name: JUPYTER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: application-password
                      name: "${APPLICATION_NAME}"
                - name: JUPYTER_ENABLE_LAB
                  value: "yes"
                - name: ANTSPATH
                  value: "/usr/local/ants/bin"
              resources:
                requests:
                  cpu: 500m
                  memory: 2Gi
                limits:
                  cpu: '8'
                  memory: 16Gi