---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: virtuoso-triplestore
  annotations:
    openshift.io/display-name: Virtuoso triplestore
    description: |-
      Start a OpenLink Virtuoso triplestore, with a SPARQL endpoint

      You can start Virtuoso using 2 different popular images:
      - Official OpenLink Virtuoso image (uses /database to store the data)
      openlink/virtuoso-opensource-7:latest
      - Alternative tenforce/virtuoso image (uses /data to store the data)
      tenforce/virtuoso:latest

      Visit https://github.com/openlink/virtuoso-opensource for more details about the Virtuoso triplestore
      Visit https://hub.docker.com/r/openlink/virtuoso-opensource-7 for more details about the image
      Visit https://github.com/vemonet/virtuoso-ldp to enable the Linked Data Platform feature
    iconClass: icon-kubevirt
    tags: triplestore,graph,database,rdf,sparql
    openshift.io/provider-display-name: Institute of Data Science, UM
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-database#start-virtuoso-triplestore
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
labels:
  template: virtuoso-triplestore
parameters:
- name: APPLICATION_NAME
  displayName: Application name
  description: Must be without spaces (use -), and unique in the project.
  value: virtuoso
  required: true
- name: PASSWORD
  displayName: Triplestore admin password
  description: The password of the dba user.
  # from: "[a-zA-Z0-9]{16}"
  # generate: expression
  required: true
- name: STORAGE_SIZE
  displayName: Storage size
  description: Size of the storage used for the notebook (approximate).
  value: 10Gi
  required: true
- name: APPLICATION_IMAGE
  displayName: Application Docker image
  description: Docker image to deploy the Virtuoso triplestore
  value: openlink/virtuoso-opensource-7:latest
  required: true
- name: DATABASE_PATH
  displayName: The database storage path
  description: Change it to /data for the tenforce/virtuoso image
  value: /database
  required: true
- name: DEFAULT_GRAPH
  displayName: Triplestore default graph
  description: The default graph used by the Virtuoso triplestore
  value: https://w3id.org/um/graph
  required: true
- name: TRIPLESTORE_URL
  displayName: URL where the triplestore will be publicly deployed
  description: Only used to define the URL of data added via the DAV Linked Data Platform
  value: https://w3id.org/um/data/
  required: true
- name: LOG_LEVEL
  displayName: Triplestore log level
  description: "Amount of log produced: 0 is minimum, 7 is maximum"
  value: "0"
  required: true

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-password: "{.data['application-password']}"
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  stringData:
    application-password: "${PASSWORD}"
    
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    accessModes:
      - "ReadWriteMany"
    resources:
      requests:
        storage: ${STORAGE_SIZE}

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: ${APPLICATION_IMAGE}
      importPolicy:
        scheduled: false
    lookupPolicy:
      local: true

- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ConfigChange
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    template:
      metadata:
        annotations:
          io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        runtimeClassName: selinux
        serviceAccountName: anyuid
        # nodeSelector:
        #   dsri.unimaas.nl/cpu: 'true'
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}"
        containers:
        - name: virtuoso-triplestore
          image: ${APPLICATION_NAME}:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8890
            protocol: TCP
          - containerPort: 1111
            protocol: TCP
          resources:
            limits:
              cpu: '32'
              memory: 200Gi
            requests:
              cpu: '2'
              memory: 4Gi
          # resources:
          #   limits:
          #     cpu: '64'
          #     memory: 200Gi
          #   requests:
          #     cpu: '2'
          #     memory: 4Gi
          volumeMounts:
          - name: data
            mountPath: "/database"
            # mountPath: "${DATABASE_PATH}"
          env:
          # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
          # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
          # https://github.com/tenforce/docker-virtuoso/blob/master/virtuoso.ini
          - name: DBA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: application-password
                name: "${APPLICATION_NAME}"
          - name: DAV_PASSWORD
            valueFrom:
              secretKeyRef:
                key: application-password
                name: "${APPLICATION_NAME}"
          - name: SPARQL_UPDATE
            value: "true"
          - name: DEFAULT_GRAPH
            value: "${DEFAULT_GRAPH}"
          - name: VIRT_Database_ErrorLogLevel
            value: "${LOG_LEVEL}"
          - name: VIRT_SPARQL_ShortenLongURIs
            value: "1"
          - name: VIRT_SPARQL_MaxCacheExpiration
            value: "1"
          - name: VIRT_SPARQL_ExternalQuerySource
            value: "1"
          - name: VIRT_SPARQL_ExternalXsltSource
            value: "1"
          - name: VIRT_SPARQL_ResultSetMaxRows
            value: "1048576"
          - name: VIRT_SPARQL_MaxQueryCostEstimationTime
            value: "100000"
          - name: VIRT_SPARQL_MaxQueryExecutionTime
            value: "6000"
          - name: VIRT_VDB_VDBDisconnectTimeout
            value: "7200000"
          - name: VIRT_Client_SQL_QUERY_TIMEOUT
            value: "14400000"
          - name: VIRT_CLient_SQL_TXN_TIMEOUT
            value: "14400000"
          - name: VIRT_Parameters_Timeout
            value: "7200"
          - name: VIRT_Parameters_TransactionAfterImageLimit
            value: "5000000000"
          - name: VIRT_Parameters_NumberOfBuffers
            value: "493674"
            # To use up to 4G of RAM according to documentation
          - name: VIRT_Parameters_TempDBSize
            value: "100000000"
          - name: VIRT_Database_MaxCheckpointRemap
            value: "125000"
          - name: VIRT_TempDatabase_MaxCheckpointRemap
            value: "125000"
          - name: VIRT_URIQA_DefaultHost
            value: "${TRIPLESTORE_URL}"
            # URL used as base for generated URI (e.g. graph in webDAV)
          # - name: VIRT_Parameters_DirsAllowed
          #   value: "., /data, /opt/virtuoso-opensource/vad, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db"
        automountServiceAccountToken: false

- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8890-tcp
      protocol: TCP
      port: 8890
      targetPort: 8890
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    host: ''
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8890-tcp
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
