---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    description: |-
      Start JupyterLab to run CUDA and PyTorch using a GPU
      with the root user.
      
      By default the GPU will not be enabled, so you can start
      this workspace to prepare your code and data. Once your the GPU has been enabled
      in your project, you can enable the GPU in your workspace with this command
      (replace jupyterlab-gpu-pytorch with the name of your deployment)
      
      oc patch deployment/jupyterlab-gpu-pytorch
      --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/resources",
      "value": {"requests": {"nvidia.com/gpu": 1}, "limits": {"nvidia.com/gpu": 1}}}]'
      
      📂 Use the `/workspace/persistent` folder (workspace of the JupyterLab UI) to store your data in the persistent
      storage
      
      🐳 You can directly use the following Docker images to work on GPU:
      - CUDA build, based on https://ngc.nvidia.com/catalog/containers/nvidia:cuda
      ghcr.io/maastrichtu-ids/jupyterlab:cuda
      - Tensorflow build, based on https://ngc.nvidia.com/catalog/containers/nvidia:tensorflow
      ghcr.io/maastrichtu-ids/jupyterlab:gpu-tensorflow
      - PyTorch build, based on https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
      ghcr.io/maastrichtu-ids/jupyterlab:gpu-pytorch
      - FSL, built with NeuroDocker and CUDA:
      ghcr.io/maastrichtu-ids/jupyterlab:fsl-gpu
      
      Feel free to check how the GPU images are built and to customize them for your project:
      https://github.com/MaastrichtU-IDS/jupyterlab
      
      🔧 You can find an
      example for PyTorch in the following repository:
      https://gitlab.maastrichtuniversity.nl/dsri-examples/dsri-pytorch-workspace
      
      🗑️
      Use this command with your application name to delete completely your application
      and its persistent volumes:
      oc delete all,pvc,secret,configmaps,serviceaccount,rolebinding
      --selector app=$APPLICATION_NAME
    iconClass: icon-python
    openshift.io/display-name: JupyterLab with PyTorch on GPU
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs/deploy-on-gpu
    openshift.io/provider-display-name: Research Computing Support, UM
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
    tags: python,jupyter,gpu,pytorch
  name: jupyterlab-gpu-pytorch
  namespace: openshift
  labels:
    template: jupyterlab-gpu-pytorch

parameters:
- name: APPLICATION_NAME
  description: Must be unique in the project. It will be used to generate the application URL.
  displayName: Application name
  required: true
  value: jupyterlab-gpu-pytorch
- name: IMAGE_NAME
  description: Check the description on the right for more details about available images
  displayName: Docker image used
  required: true
  value: ghcr.io/maastrichtu-ids/jupyterlab:gpu-pytorch
- name: STORAGE_SIZE
  description: Size of the storage allocated to the notebook persistent storage in `/workspace/persistent`.
  displayName: Storage size
  required: true
  value: 20Gi

#Custom parameters 
- name: JUPYTER_TOKEN
  description: The password, aka. token, to access the notebook
  displayName: Notebook password
  required: true
- name: GIT_NAME
  description: Email used to automatically define git config --global user.name
  displayName: Git name
  required: true
  value: default
- name: GIT_EMAIL
  description: Email used to automatically define git config --global user.email
  displayName: Git email
  required: true
  value: default@maastrichtuniversity.nl
- name: IMAGE_PULL_POLICY
  description: Use Always to make sure the new image is pulled when you update it
  displayName: Image pull policy
  required: true
  value: IfNotPresent

objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "${STORAGE_SIZE}"
    storageClassName: ocs-storagecluster-cephfs
    
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: 6006-tcp
      port: 6006
      protocol: TCP
      targetPort: 6006
    selector:
      app: "${APPLICATION_NAME}"
      deployment: "${APPLICATION_NAME}"

- kind: Service
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    host: ''
    port:
      targetPort: 8888-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100

- kind: Secret
  apiVersion: v1
  metadata:
    annotations:
      template.openshift.io/expose-password: "{.data['application-password']}"
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  stringData:
    application-password: "${JUPYTER_TOKEN}"

- kind: Deployment
  apiVersion: apps/v1
  metadata:
    labels:
      app: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "${APPLICATION_NAME}"
        deployment: "${APPLICATION_NAME}"
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deployment: "${APPLICATION_NAME}"
      spec:
        containers:
        - env:
          - name: JUPYTER_TOKEN
            valueFrom:
              secretKeyRef:
                key: application-password
                name: "${APPLICATION_NAME}"
          - name: GIT_NAME
            value: "${GIT_NAME}"
          - name: GIT_EMAIL
            value: "${GIT_EMAIL}"
          - name: WORKSPACE
            value: "/workspace"
          - name: PERSISTENT_FOLDER
            value: "/workspace/persistent"
          image: "${IMAGE_NAME}"
          imagePullPolicy: "${IMAGE_PULL_POLICY}"
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 8888
            protocol: TCP
          - containerPort: 6006
            protocol: TCP
          resources:
            limits:
              cpu: '64'
              memory: 256Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - mountPath: "/dev/shm"
            name: dshm
          - mountPath: "/workspace/persistent"
            name: data
        serviceAccountName: anyuid
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
        - name: data
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}"