apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nvidia-pytorch-gpu
spec:
  lookupPolicy:
    local: true
  tags: 
    - name: 19.12-py3
      from: 
        kind: DockerImage
        name: nvcr.io/nvidia/pytorch:19.12-py3