apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: wildfly-s2i-chained-build-template
metadata:
  annotations:
    description: S2I build of WildFly application (<app-name>-build-artifacts image)
      followed by a build to create a lightweight application image (<app-name> image).
      <app-name> image can then be managed by the WildFly Operator.
    iconClass: icon-wildfly
    openshift.io/display-name: WildFly S2I Chained Build
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.13.0-0.okd-2023-09-30-084937
    template.openshift.io/long-description: S2I build of WildFly application (<app-name>-build-artifacts
      image) followed by a build to create a lightweight application image (<app-name>
      image). <app-name> image can then be managed by the WildFly Operator.
  creationTimestamp: "2021-05-27T13:39:32Z"
  labels:
    samples.operator.openshift.io/managed: "true"
  name: wildfly-s2i-chained-build-template
  namespace: openshift
  resourceVersion: "3123306826"
  uid: 25c34d77-f491-4701-aa87-770a0c1aee12
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}-build-artifacts
    name: ${APPLICATION_NAME}-build-artifacts
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}-build-artifacts
    name: ${APPLICATION_NAME}-build-artifacts
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-build-artifacts:latest
    runPolicy: Serial
    source:
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: GALLEON_PROVISION_LAYERS
          value: ${GALLEON_PROVISION_LAYERS}
        - name: GALLEON_PROVISION_DEFAULT_FAT_SERVER
          value: "true"
        from:
          kind: ImageStreamTag
          name: wildfly:latest
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - imageChange: null
      type: ImageChange
    - type: ConfigChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      dockerfile: "FROM wildfly-runtime-centos7:latest\nCOPY /server $JBOSS_HOME\nUSER
        root\nRUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME\nRUN
        ln -s $JBOSS_HOME /wildfly \nUSER jboss\nCMD $JBOSS_HOME/bin/openshift-launch.sh"
      images:
      - from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-build-artifacts:latest
        paths:
        - destinationDir: .
          sourcePath: /s2i-output/server/
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly-runtime:latest
          namespace: ${IMAGE_STREAM_NAMESPACE}
        imageOptimizationPolicy: SkipLayers
      type: Docker
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-build-artifacts:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The application name. Name is assigned to all of the application objects
    defined in this template.
  displayName: Image Name
  name: APPLICATION_NAME
  required: true
  value: wildfly-app
- description: The application git repository
  displayName: git repository
  name: GIT_REPO
  required: true
  value: https://github.com/openshift/openshift-jee-sample.git
- description: The application git repository sub directory
  displayName: git repository sub directory
  name: GIT_CONTEXT_DIR
- description: The application git branch
  displayName: git branch
  name: GIT_BRANCH
  value: master
- description: Namespace in which the ImageStreams for WildFly images are installed.
    These ImageStreams are normally installed in the openshift namespace. You should
    only need to modify this if you've installed the ImageStreams in a different namespace/project.
  displayName: ImageStreams Namespace
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: A comma separated lists of galleon layers to provision. The main layers
    are cloud-server, jaxrs-server and datasources-web-server. You can check documentation
    to get more details on layers.
  displayName: List of Galleon layers.
  name: GALLEON_PROVISION_LAYERS
