apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: custom-workspace
metadata:
  annotations:
    description: "Use this template to start a custom Docker image, and easily run
      your code through a web UI exposed on port 8888, such as JupyterLab or VSCode\n\n\U0001F4E6
      We recommend you to use `conda install` to install new packages, but you can
      also use `sudo apt-get install` or `pip install`\n\n\U0001F4C2 Use the workspace
      of the web UI (/root usually) to store your data in the persistent storage automatically
      created\nYou can find the persistent storage in the DSRI web UI, go to Administrator
      view > Storage > Persistent Volume Claims\n\n\U0001F433 Docker images, see https://github.com/MaastrichtU-IDS/jupyterlab
      for more details\n- Ricopili package:\nghcr.io/maastrichtu-ids/jupyterlab:ricopili\n-
      JupyterLab with python2.7:\nghcr.io/maastrichtu-ids/jupyterlab:python2.7\n\nShould
      work with most basic Docker image if the web UI is exposed on port 8888"
    iconClass: icon-beaker
    kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"template.openshift.io/v1\",\"kind\":\"Template\",\"labels\":{\"template\":\"custom-workspace\"},\"metadata\":{\"annotations\":{\"description\":\"Use
      this template to start a custom Docker image, and easily run your code through
      a web UI exposed on port 8888, such as JupyterLab or VSCode\\n\\n\U0001F4E6
      We recommend you to use `conda install` to install new packages, but you can
      also use `sudo apt-get install` or `pip install`\\n\\n\U0001F4C2 Use the workspace
      of the web UI (/root usually) to store your data in the persistent storage automatically
      created\\nYou can find the persistent storage in the DSRI web UI, go to Administrator
      view \\u003e Storage \\u003e Persistent Volume Claims\\n\\n\U0001F433 Docker
      images, see https://github.com/MaastrichtU-IDS/jupyterlab for more details\\n-
      Ricopili package:\\nghcr.io/maastrichtu-ids/jupyterlab:ricopili\\n- JupyterLab
      with python2.7:\\nghcr.io/maastrichtu-ids/jupyterlab:python2.7\\n\\nShould work
      with most basic Docker image if the web UI is exposed on port 8888\",\"iconClass\":\"icon-beaker\",\"openshift.io/display-name\":\"Custom
      workspace\",\"openshift.io/documentation-url\":\"https://maastrichtu-ids.github.io/dsri-documentation/docs\",\"openshift.io/provider-display-name\":\"Institute
      of Data Science, UM\",\"openshift.io/support-url\":\"https://maastrichtu-ids.github.io/dsri-documentation/help\",\"tags\":\"custom,interface,root\"},\"name\":\"custom-workspace\",\"namespace\":\"openshift\"},\"objects\":[{\"apiVersion\":\"image.openshift.io/v1\",\"kind\":\"ImageStream\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"spec\":{\"lookupPolicy\":{\"local\":true},\"tags\":[{\"from\":{\"kind\":\"DockerImage\",\"name\":\"${APPLICATION_IMAGE}\"},\"importPolicy\":{\"scheduled\":false},\"name\":\"latest\"}]}},{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"spec\":{\"accessModes\":[\"ReadWriteMany\"],\"resources\":{\"requests\":{\"storage\":\"${STORAGE_SIZE}\"}}}},{\"apiVersion\":\"v1\",\"kind\":\"Secret\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"stringData\":{\"application-password\":\"${PASSWORD}\"}},{\"apiVersion\":\"v1\",\"kind\":\"DeploymentConfig\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"spec\":{\"replicas\":1,\"selector\":{\"app\":\"${APPLICATION_NAME}\",\"deploymentconfig\":\"${APPLICATION_NAME}\"},\"strategy\":{\"type\":\"Recreate\"},\"template\":{\"metadata\":{\"annotations\":{\"io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel\":\"true\"},\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"deploymentconfig\":\"${APPLICATION_NAME}\"}},\"spec\":{\"automountServiceAccountToken\":false,\"containers\":[{\"env\":[{\"name\":\"JUPYTER_TOKEN\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"application-password\",\"name\":\"${APPLICATION_NAME}\"}}},{\"name\":\"PASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"application-password\",\"name\":\"${APPLICATION_NAME}\"}}}],\"image\":\"${APPLICATION_NAME}:latest\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"custom-app\",\"ports\":[{\"containerPort\":8888,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"cpu\":\"32\",\"memory\":\"200Gi\"},\"requests\":{\"cpu\":\"2\",\"memory\":\"4Gi\"}},\"volumeMounts\":[{\"mountPath\":\"${WORKDIR}\",\"name\":\"data\"},{\"mountPath\":\"/dev/shm\",\"name\":\"dshm\"}]}],\"runtimeClassName\":\"selinux\",\"serviceAccountName\":\"anyuid\",\"volumes\":[{\"name\":\"data\",\"persistentVolumeClaim\":{\"claimName\":\"${APPLICATION_NAME}\"}},{\"emptyDir\":{\"medium\":\"Memory\"},\"name\":\"dshm\"}]}},\"triggers\":[{\"type\":\"ConfigChange\"},{\"imageChangeParams\":{\"automatic\":true,\"containerNames\":[\"custom-app\"],\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"${APPLICATION_NAME}:latest\"}},\"type\":\"ImageChange\"}]}},{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"spec\":{\"ports\":[{\"name\":\"8888-tcp\",\"port\":8888,\"protocol\":\"TCP\",\"targetPort\":8888}],\"selector\":{\"app\":\"${APPLICATION_NAME}\",\"deploymentconfig\":\"${APPLICATION_NAME}\"},\"type\":\"ClusterIP\"}},{\"apiVersion\":\"v1\",\"kind\":\"Route\",\"metadata\":{\"labels\":{\"app\":\"${APPLICATION_NAME}\",\"template\":\"custom-workspace\"},\"name\":\"${APPLICATION_NAME}\"},\"spec\":{\"host\":\"\",\"port\":{\"targetPort\":\"8888-tcp\"},\"tls\":{\"insecureEdgeTerminationPolicy\":\"Redirect\",\"termination\":\"edge\"},\"to\":{\"kind\":\"Service\",\"name\":\"${APPLICATION_NAME}\",\"weight\":100}}}],\"parameters\":[{\"description\":\"Must
      be without spaces (use -), and unique in the project.\",\"displayName\":\"Name
      for the application\",\"name\":\"APPLICATION_NAME\",\"required\":true,\"value\":\"custom-workspace\"},{\"description\":\"The
      password to access the web UI\",\"displayName\":\"Web UI Password\",\"name\":\"PASSWORD\",\"required\":true},{\"description\":\"Docker
      image of your application in a public registry\",\"displayName\":\"Docker image\",\"name\":\"APPLICATION_IMAGE\",\"required\":true,\"value\":\"ghcr.io/maastrichtu-ids/jupyterlab:ricopili\"},{\"description\":\"Size
      of the storage allocated to the notebook persistent storage.\",\"displayName\":\"Storage
      size\",\"name\":\"STORAGE_SIZE\",\"required\":true,\"value\":\"5Gi\"},{\"description\":\"The
      working directory in your container (will be stored persistently). This depends
      on the image, refer to the description on the right, or the image docs.\",\"displayName\":\"Working
      directory\",\"name\":\"WORKDIR\",\"required\":true,\"value\":\"/root\"}]}\n"
    openshift.io/display-name: Custom workspace
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs
    openshift.io/provider-display-name: Institute of Data Science, UM
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
    tags: custom,interface,root
  creationTimestamp: "2021-07-06T18:27:33Z"
  name: custom-workspace
  namespace: openshift
  resourceVersion: "3786736839"
  uid: e66b621a-94ae-47c5-bd23-276545376b67
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: ${APPLICATION_IMAGE}
      importPolicy:
        scheduled: false
      name: latest
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  stringData:
    application-password: ${PASSWORD}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: "true"
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        automountServiceAccountToken: false
        containers:
        - env:
          - name: JUPYTER_TOKEN
            valueFrom:
              secretKeyRef:
                key: application-password
                name: ${APPLICATION_NAME}
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: application-password
                name: ${APPLICATION_NAME}
          image: ${APPLICATION_NAME}:latest
          imagePullPolicy: IfNotPresent
          name: custom-app
          ports:
          - containerPort: 8888
            protocol: TCP
          resources:
            limits:
              cpu: "32"
              memory: 200Gi
            requests:
              cpu: "2"
              memory: 4Gi
          volumeMounts:
          - mountPath: ${WORKDIR}
            name: data
          - mountPath: /dev/shm
            name: dshm
        runtimeClassName: selinux
        serviceAccountName: anyuid
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ${APPLICATION_NAME}
        - emptyDir:
            medium: Memory
          name: dshm
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: false
        containerNames:
        - custom-app
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      template: custom-workspace
    name: ${APPLICATION_NAME}
  spec:
    host: ""
    port:
      targetPort: 8888-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
parameters:
- description: Must be without spaces (use -), and unique in the project.
  displayName: Name for the application
  name: APPLICATION_NAME
  required: true
  value: custom-workspace
- description: The password to access the web UI
  displayName: Web UI Password
  name: PASSWORD
  required: true
- description: Docker image of your application in a public registry
  displayName: Docker image
  name: APPLICATION_IMAGE
  required: true
  value: ghcr.io/maastrichtu-ids/jupyterlab:ricopili
- description: Size of the storage allocated to the notebook persistent storage.
  displayName: Storage size
  name: STORAGE_SIZE
  required: true
  value: 5Gi
- description: The working directory in your container (will be stored persistently).
    This depends on the image, refer to the description on the right, or the image
    docs.
  displayName: Working directory
  name: WORKDIR
  required: true
  value: /root
