---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: filebrowser
  annotations:
    openshift.io/display-name: File Browser for existing storage
    description: |-
      Deploy a filebrowser on your persistent volume. This will provide a web UI to upload and download data to your DSRI persistent volume.

      🔑 Default login is admin, with the password you set.

      📂 Note that we use the `/filebrowser` folder in the container (workspace of the Filebrowser UI) to access the data in the existing persistent storage
    iconClass: icon-load-balancer
    tags: filebrowser,storage
    openshift.io/provider-display-name: Research Computing Support, UM
    openshift.io/documentation-url: https://maastrichtu-ids.github.io/dsri-documentation/docs/catalog-utilities#file-browser
    openshift.io/support-url: https://maastrichtu-ids.github.io/dsri-documentation/help
labels:
  template: filebrowser
message: The filebrowser has been deployed. Login with admin and the password you set.

parameters:
  - name: APPLICATION_NAME
    displayName: Application name
    description: Must be without spaces (use -), and unique in the project.
    value: filebrowser
    required: true
  - name: PASSWORD
    displayName: Application password
    description: The plain-text password to login with admin in the filebrowser
    required: true
  - name: STORAGE_NAME
    displayName: Storage name
    description: Name of the Persistent Volume Claim that will be exposed by the filebrowser.
    value: storage-name
    required: true
  - name: STORAGE_FOLDER
    displayName: Storage folder
    description: Path to the folder used to store your application data in the the Persistent Volume Claim (leave empty to use the root folder of the storage)
    required: false

objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      selector:
        app: "${APPLICATION_NAME}"
      ports:
        - name: "80-tcp"
          protocol: TCP
          port: 80
          targetPort: 80

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      to:
        kind: Service
        name: "${APPLICATION_NAME}"
      port:
        targetPort: "80-tcp"
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    stringData:
      application-password: "${PASSWORD}"

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: "${APPLICATION_NAME}"
      labels:
        app: "${APPLICATION_NAME}"
    spec:
      replicas: 1
      strategy:
        type: Recreate
      selector:
        matchLabels:
          app: "${APPLICATION_NAME}"
      template:
        metadata:
          annotations:
            io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
          labels:
            app: "${APPLICATION_NAME}"
            deployment: "${APPLICATION_NAME}"
        spec:
          runtimeClassName: selinux
          serviceAccountName: anyuid
          automountServiceAccountToken: false
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: "${STORAGE_NAME}"
            - name: filebrowser-db
              emptyDir: {}
          initContainers:
            - name: init-filebrowser-db
              image: ghcr.io/maastrichtu-ids/filebrowser:v2.11.0
              args:
                - "-d"
                - "/database/filebrowser.db"
                - "config"
                - "init"
              volumeMounts:
                - name: filebrowser-db
                  mountPath: /database
            - name: init-filebrowser-user
              image: ghcr.io/maastrichtu-ids/filebrowser:v2.11.0
              args:
                - "-d"
                - "/database/filebrowser.db"
                - "users"
                - "add"
                - "admin"
                - "$(PASSWORD)"
                - "--perm.admin"
              env:
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: application-password
                      name: "${APPLICATION_NAME}"
              volumeMounts:
                - name: filebrowser-db
                  mountPath: /database
          containers:
            - name: "${APPLICATION_NAME}"
              image: ghcr.io/maastrichtu-ids/filebrowser:v2.11.0
              imagePullPolicy: IfNotPresent
              args:
                - "--root"
                - "/filebrowser"
                - "--database"
                - "/database/filebrowser.db"
              ports:
                - containerPort: 80
                  protocol: TCP
              volumeMounts:
                - name: data
                  mountPath: "/filebrowser"
                  subPath: "${STORAGE_FOLDER}"
                - name: filebrowser-db
                  mountPath: /database
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                  ephemeral-storage: 1Gi
                limits:
                  cpu: '1'
                  memory: 2Gi
                  ephemeral-storage: 5Gi