name: Publish FSL with GPU image
env:
  IMAGE_ID: ghcr.io/maastrichtu-ids/jupyterlab:fsl-gpu

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
    - 'applications/gpu/fsl-gpu/Dockerfile'
    - '.github/workflows/docker-fsl-gpu.yml'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file applications/gpu/fsl-gpu/Dockerfile --tag $IMAGE_ID

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker push $IMAGE_ID
