name: Publish to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

    - name: Build and publish
      env:
        USE_SSH: true
        GIT_USER: MaastrichtU-IDS
      run: |
        git config --global user.email "vincent.emonet@maastrichtuniversity.nl"
        git config --global user.name "Vincent Emonet"
        cd website
        yarn install
        yarn deploy
      # GIT_USER=MaastrichtU-IDS CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages
