apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Workspace\path\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: docworker
  name: docworker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: docworker
    spec:
      containers:
      - image: datastewardshipwizard/document-worker:2.10.0
        name: docworker
        resources: {}
      restartPolicy: Always
status: {}
