apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Workspace\path\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dsw-client
  name: dsw-client
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: dsw-client
status:
  loadBalancer: {}
