apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Workspace\path\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dsw-server
  name: dsw-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dsw-server
    spec:
      containers:
      - image: datastewardshipwizard/wizard-server:2.10.0
        name: dsw-server
        ports:
        - containerPort: 3000
        resources: {}
      hostname: dsw_server
      restartPolicy: Always
status: {}
