apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Workspace\path\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dsw-server
  name: dsw-server
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: dsw-server
status:
  loadBalancer: {}
